---
name: rustfmt
description: A tool for formatting Rust code according to style guidelines.
homepage: https://github.com/rust-lang/rustfmt
licenses:
  - Apache-2.0
  - MIT
languages:
  - Rust
categories:
  - Formatter

source:
  id: pkg:generic/rustfmt@x
  build:
    run: cp $(which rustfmt) . || echo "rustfmt not found"
    bin: rustfmt

bin:
  rustfmt: "{{source.build.bin}}"
