---
name: rustfmt
description: A tool for formatting Rust code according to style guidelines.
homepage: https://github.com/rust-lang/rustfmt
licenses:
  - Apache-2.0
  - MIT
languages:
  - Rust
categories:
  - Formatter
source:
  # renovate:datasource=github-tags
  id: pkg:github/rust-lang/rustfmt@@v1.5.2
  build:
    - target: win
      run: |
        cargo build --release
      rustfmt: target/release/rustfmt.exe
    - target: win
      run: |
        cargo build --release
      rustfmt: target/release/rustfmt
bin:
  rustfmt: "{{source.build.rustfmt}}"
